import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const TEMPLATES = [
  {
    name: 'Modern Executive (Analyst Skill)',
    description:
      'Official corporate certification layout with geometric navy accents, verification QR code, dual executive signatures, and official center seal.',
    isActive: true,
    version: 1,
    fields: [
      {
        key: 'companyLogo',
        x: 8,
        y: 8,
        width: 140,
        height: 45,
        visible: true,
        text: 'Analyst Skill',
      },
      {
        key: 'qrCode',
        x: 8,
        y: 19,
        size: 70,
        visible: true,
      },
      {
        key: 'verifiedBadge',
        x: 92,
        y: 8,
        size: 40,
        visible: true,
        text: 'VERIFIED',
      },
      {
        key: 'certificateTitle',
        x: 50,
        y: 18,
        size: 28,
        bold: true,
        color: '#1e293b',
        align: 'center',
        text: 'Certificate of Training',
      },
      {
        key: 'preamble',
        x: 50,
        y: 25,
        size: 12,
        bold: false,
        color: '#334155',
        align: 'center',
        text: 'THIS IS TO CERTIFY THAT',
      },
      {
        key: 'holderName',
        x: 50,
        y: 35,
        size: 30,
        bold: true,
        color: '#0f172a',
        align: 'center',
      },
      {
        key: 'completionText',
        x: 50,
        y: 43,
        size: 13,
        bold: false,
        color: '#475569',
        align: 'center',
        text: 'has successfully completed the training course',
      },
      {
        key: 'courseTitle',
        x: 50,
        y: 51,
        size: 22,
        bold: true,
        color: '#0f172a',
        align: 'center',
      },
      {
        key: 'courseDescription',
        x: 50,
        y: 58,
        size: 12,
        bold: false,
        color: '#475569',
        align: 'center',
        text: 'by participating & completing all modules and passing all evaluation tests.',
      },
      {
        key: 'courseHours',
        x: 12,
        y: 67,
        size: 12,
        bold: false,
        color: '#1e293b',
        align: 'left',
      },
      {
        key: 'issuedAt',
        x: 88,
        y: 67,
        size: 12,
        bold: false,
        color: '#1e293b',
        align: 'right',
      },
      {
        key: 'stamp',
        x: 50,
        y: 78,
        size: 85,
        visible: true,
        text: 'Analyst Skill eLearning',
        title: 'Issued by: Analyst Skill eLearning',
      },
      {
        key: 'signature1',
        x: 18,
        y: 80,
        width: 120,
        height: 45,
        visible: true,
        text: 'MD. Morshedul Alam ACMA',
        title: 'CEO, Analyst Skill',
      },
      {
        key: 'signature2',
        x: 82,
        y: 80,
        width: 120,
        height: 45,
        visible: true,
        text: 'MD. Morshedul Alam ACMA',
        title: 'Founder & CEO, Analyst Skill e-Learning',
      },
      {
        key: 'footerNote',
        x: 50,
        y: 96,
        size: 9,
        color: '#64748b',
        align: 'center',
        text: '~ Analyst Skill is a professional e-Learning platform. To know more about us, please visit: https://www.analystskill.com ~',
      },
    ],
  },
  {
    name: 'Ministry of Revenues Official (Gold & Navy)',
    description:
      'Formal governmental certificate template with official Ministry of Revenues seal, gold framing, and authorized ministerial registrar credentials.',
    isActive: false,
    version: 1,
    fields: [
      {
        key: 'companyLogo',
        x: 50,
        y: 8,
        width: 80,
        height: 50,
        visible: true,
        text: 'Ministry of Revenues',
      },
      {
        key: 'qrCode',
        x: 88,
        y: 12,
        size: 65,
        visible: true,
      },
      {
        key: 'verifiedBadge',
        x: 12,
        y: 12,
        size: 40,
        visible: true,
        text: 'OFFICIAL ACCREDITED',
      },
      {
        key: 'certificateTitle',
        x: 50,
        y: 20,
        size: 26,
        bold: true,
        color: '#1e3a8a',
        align: 'center',
        text: 'Certificate of Competency & Accreditation',
      },
      {
        key: 'preamble',
        x: 50,
        y: 27,
        size: 12,
        bold: false,
        color: '#475569',
        align: 'center',
        text: 'THIS IS TO OFFICIALLY CERTIFY THAT',
      },
      {
        key: 'holderName',
        x: 50,
        y: 37,
        size: 28,
        bold: true,
        color: '#0f172a',
        align: 'center',
      },
      {
        key: 'completionText',
        x: 50,
        y: 44,
        size: 13,
        bold: false,
        color: '#334155',
        align: 'center',
        text: 'has successfully fulfilled all statutory curriculum & assessment criteria for',
      },
      {
        key: 'courseTitle',
        x: 50,
        y: 52,
        size: 22,
        bold: true,
        color: '#1e3a8a',
        align: 'center',
      },
      {
        key: 'courseDescription',
        x: 50,
        y: 59,
        size: 12,
        bold: false,
        color: '#64748b',
        align: 'center',
        text: 'conducted under the auspices of the Ministry of Revenues Training Directorate.',
      },
      {
        key: 'courseHours',
        x: 14,
        y: 68,
        size: 12,
        bold: false,
        color: '#334155',
        align: 'left',
      },
      {
        key: 'issuedAt',
        x: 86,
        y: 68,
        size: 12,
        bold: false,
        color: '#334155',
        align: 'right',
      },
      {
        key: 'stamp',
        x: 50,
        y: 78,
        size: 90,
        visible: true,
        text: 'Official Seal · MoR Ethiopia',
        title: 'Ministry of Revenues Directorate',
      },
      {
        key: 'signature1',
        x: 20,
        y: 80,
        width: 120,
        height: 45,
        visible: true,
        text: 'Abebe Bikila',
        title: 'Director of Training & Capacity Development',
      },
      {
        key: 'signature2',
        x: 80,
        y: 80,
        width: 120,
        height: 45,
        visible: true,
        text: 'Mulugeta Tesfaye',
        title: 'Registrar General, Ministry of Revenues',
      },
      {
        key: 'footerNote',
        x: 50,
        y: 96,
        size: 9,
        color: '#64748b',
        align: 'center',
        text: 'Federal Democratic Republic of Ethiopia · Ministry of Revenues · ETIMS Academy',
      },
    ],
  },
  {
    name: 'Tech Sleek Minimalist',
    description:
      'Contemporary digital skills certificate with clean typography, cyan accent framing, digital signature, and cryptographic verification hash.',
    isActive: false,
    version: 1,
    fields: [
      {
        key: 'companyLogo',
        x: 10,
        y: 10,
        width: 120,
        height: 40,
        visible: true,
        text: 'TechAcademy',
      },
      {
        key: 'qrCode',
        x: 88,
        y: 12,
        size: 65,
        visible: true,
      },
      {
        key: 'verifiedBadge',
        x: 90,
        y: 30,
        size: 35,
        visible: true,
        text: 'VERIFIED CREDENTIAL',
      },
      {
        key: 'certificateTitle',
        x: 10,
        y: 24,
        size: 24,
        bold: true,
        color: '#0284c7',
        align: 'left',
        text: 'Certificate of Digital Mastery',
      },
      {
        key: 'preamble',
        x: 10,
        y: 31,
        size: 11,
        bold: false,
        color: '#64748b',
        align: 'left',
        text: 'PROUDLY PRESENTED TO',
      },
      {
        key: 'holderName',
        x: 10,
        y: 40,
        size: 32,
        bold: true,
        color: '#0f172a',
        align: 'left',
      },
      {
        key: 'completionText',
        x: 10,
        y: 48,
        size: 12,
        bold: false,
        color: '#64748b',
        align: 'left',
        text: 'for successfully completing the rigorous practical and theoretical requirements of',
      },
      {
        key: 'courseTitle',
        x: 10,
        y: 56,
        size: 22,
        bold: true,
        color: '#0f172a',
        align: 'left',
      },
      {
        key: 'courseHours',
        x: 10,
        y: 66,
        size: 12,
        bold: false,
        color: '#475569',
        align: 'left',
      },
      {
        key: 'issuedAt',
        x: 50,
        y: 66,
        size: 12,
        bold: false,
        color: '#475569',
        align: 'left',
      },
      {
        key: 'signature1',
        x: 20,
        y: 82,
        width: 120,
        height: 45,
        visible: true,
        text: 'Dr. Sarah Jenkins',
        title: 'Lead Instructor & Curriculum Architect',
      },
      {
        key: 'stamp',
        x: 82,
        y: 80,
        size: 80,
        visible: true,
        text: 'Certified Digital Credential',
        title: 'Cryptographically Verified',
      },
      {
        key: 'footerNote',
        x: 50,
        y: 96,
        size: 9,
        color: '#94a3b8',
        align: 'center',
        text: 'Verify this credential authenticity online at the official portal using the QR code or verification key.',
      },
    ],
  },
];

async function main() {
  console.log('Seeding 3 certificate templates...');

  for (const t of TEMPLATES) {
    const existing = await prisma.certificateTemplate.findFirst({
      where: { name: t.name },
    });

    if (existing) {
      console.log(`Updating template: ${t.name}`);
      await prisma.certificateTemplate.update({
        where: { id: existing.id },
        data: {
          description: t.description,
          isActive: t.isActive,
          version: t.version,
          fields: t.fields as unknown as Prisma.InputJsonValue,
        },
      });
    } else {
      console.log(`Creating template: ${t.name}`);
      await prisma.certificateTemplate.create({
        data: {
          name: t.name,
          description: t.description,
          isActive: t.isActive,
          version: t.version,
          fields: t.fields as unknown as Prisma.InputJsonValue,
        },
      });
    }
  }

  console.log('Certificate templates seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

